// Collection Reducer
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

export const ADD_COLLECTION_START = 'ADD_COLLECTION_START';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_FAILED = 'ADD_COLLECTION_FAILED';

export const UPDATE_COLLECTION_START = 'UPDATE_COLLECTION_START';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_FAILED = 'UPDATE_COLLECTION_FAILED';

export const REMOVE_COLLECTION_START = 'REMOVE_COLLECTION_START';
export const REMOVE_COLLECTION_SUCCESS = 'REMOVE_COLLECTION_SUCCESS';
export const REMOVE_COLLECTION_FAILED = 'REMOVE_COLLECTION_FAILED';

// Shop Reducer
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

export const ADD_PRODUCT_START = 'ADD_PRODUCT_START';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const REMOVE_PRODUCT_START = 'REMOVE_PRODUCT_START';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';

export const SELECTED_PRODUCT = 'SELECT_PRODUCT';
export const EMPTY_PRODUCTS = 'EMPTY_PRODUCTS';

export const SORT_BY_PRICE_INC = 'SORT_BY_PRICE_INC';
export const SORT_BY_PRICE_DEC = 'SORT_BY_PRICE_DEC';
export const SORT_BY_NAME_INC = 'SORT_BY_NAME_INC';
export const SORT_BY_NAME_DEC = 'SORT_BY_NAME_DEC';

// Cart Reducer
export const FETCH_CART_START = 'FETCH_CART_START';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_DB_START = 'ADD_TO_CART_DB_START';
export const ADD_TO_CART_DB_FAILED = 'ADD_TO_CART_DB_FAILED';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_DB_START = 'REMOVE_FROM_CART_DB_START';
export const REMOVE_FROM_CART_DB_FAILED = 'REMOVE_FROM_CART_DB_FAILED';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_DB_START = 'UPDATE_CART_DB_START';
export const UPDATE_CART_DB_FAILED = 'UPDATE_CART_DB_FAILED';

export const EMPTY_CART = 'EMPTY_CART';
// export const MERGE_CART = 'MERGE_CART';

// Auth Reducer
export const LOG_IN_START = 'LOG_IN_START'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';

export const LOG_OUT = 'LOG_OUT';